name: Bot Saham Harian

on:
  schedule:
    # Berjalan setiap Senin-Jumat jam 08:50 UTC (15:50 WIB)
    - cron: '50 8 * * 1-5'
  workflow_dispatch: # Agar kamu bisa klik tombol "Run" manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instal Library
        run: |
          pip install yfinance pandas pandas_ta python-telegram-bot

      - name: Jalankan Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_saham.py
