name: Bot Saham Harian

on:
  schedule:
    - cron: '50 8 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instal Library
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas==2.0.3 python-telegram-bot
          pip install pandas-ta==0.3.14b0

      - name: Jalankan Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_saham.py
