name: FAST ALL TIME BOT

on:
  schedule:
    - cron: '2 2 * * 1-5'    # 09:02 WIB
    - cron: '15 2 * * 1-5'   # 09:15 WIB
    - cron: '30 2 * * 1-5'
    - cron: '45 2 * * 1-5'
  workflow_dispatch:

jobs:
  run-fast-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install yfinance

      - name: Run FAST ALL TIME BOT
        run: python bot_fast_all_time.py
